### ISSUE TITLE
error with narrow:lines

### ISSUE THREAD

**Issue by jots** [t9md/atom-narrow#11]
on atom 1.11.1

I do a "narrow:lines"  it shows the candidates, I scroll to the one I want and hit ENTER, and this error pops up:

```
TypeError: Cannot read property 'dispose' of undefined
    at /usr/share/atom/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:25:28
    at Set.forEach (native)
    at CompositeDisposable.module.exports.CompositeDisposable.dispose (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:24:26)
    at /usr/share/atom/resources/app.asar/src/workspace.js:267:36
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.destroyed (/usr/share/atom/resources/app.asar/src/text-editor.js:529:27)
    at TextEditor.module.exports.Model.destroy (/usr/share/atom/resources/app.asar/src/model.js:31:58)
    at UI.module.exports.UI.confirm (/home/joe/.atom/packages/narrow/lib/ui.coffee:160:15)
    at atom-text-editor.atom.commands.add.core:confirm (/home/joe/.atom/packages/narrow/lib/ui.coffee:44:27)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

**Comment by t9md** [comment]
Its fixed from v0.7.0.
Sorry for unresponsiveness.
