### ISSUE TITLE
Uncaught Error: Module did not self-register At ELECTRON_ASAR.js:168

### ISSUE THREAD

**Issue by balta2ar** [t9md/atom-narrow#188]
[Enter steps to reproduce:]

1. Execute "Narrrow: Project Symbols" in command palette.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 12.04.5
**Thrown From**: [narrow](https://github.com/t9md/atom-narrow) package 0.40.0

### Stack Trace

Uncaught Error: Module did not self-register.

```
At ELECTRON_ASAR.js:168

Error: Module did not self-register.
    at Error (native)
    at process.module.(anonymous function) (ELECTRON_ASAR.js:168:20)
    at process.module.(anonymous function) (ELECTRON_ASAR.js:168:20)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:182:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /app.asar/node_modules/ctags/lib/ctags.js:4:10)
    at /app.asar/node_modules/ctags/lib/ctags.js:60:4)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /app.asar/node_modules/symbols-view/lib/tag-reader.js:13:14)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at requireFrom (/packages/narrow/lib/utils.coffee:67:3)
    at /packages/narrow/lib/provider/project-symbols.coffee:15:13)
    at /packages/narrow/lib/provider/project-symbols.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Function.module.exports.ProviderBase.start (/packages/narrow/lib/provider/provider-base.coffee:31:13)
    at Object.narrow (/packages/narrow/lib/main.coffee:116:5)
    at /packages/narrow/lib/main.coffee:45:37)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at Object.didConfirmSelection (/app.asar/node_modules/command-palette/lib/command-palette-view.js:106:29)
    at SelectListView.confirmSelection (/app.asar/node_modules/atom-select-list/src/select-list-view.js:292:20)
    at /app.asar/node_modules/atom-select-list/src/select-list-view.js:64:14)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
 15x -1:36.3.0 core:move-down (input.hidden-input)
  6x -1:22.4.0 core:move-up (input.hidden-input)
     -1:21.1.0 core:confirm (input.hidden-input)
     -0:40.4.0 intentions:highlight (input.hidden-input)
     -0:39.7.0 command-palette:toggle (input.hidden-input)
     -0:36.6.0 core:backspace (input.hidden-input)
     -0:35.3.0 core:confirm (input.hidden-input)
     -0:35.2.0 narrow:symbols (input.hidden-input)
 16x -0:33.6.0 core:move-down (input.hidden-input)
  4x -0:29.3.0 core:move-up (input.hidden-input)
     -0:28.3.0 core:confirm (input.hidden-input)
     -0:17.9.0 intentions:highlight (input.hidden-input)
     -0:17.6.0 command-palette:toggle (input.hidden-input)
     -0:14.9.0 core:backspace (input.hidden-input)
     -0:14 core:confirm (input.hidden-input)
     -0:14 narrow:project-symbols (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
aligner 0.22.3 
aligner-python 1.0.1 
asciidoc-preview 2.10.0 
atom-alignment 0.12.1 
atom-beautify 0.29.23 
atom-ctags 5.0.0 
atom-fuzzy-grep 0.16.0 
atom-html-preview 0.1.22 
atom-latex 0.7.6 
atom-math 0.0.9 
atom-monokai 0.10.9 
atom-python-run 0.7.3 
atom-terminal 0.8.0 
atom-typescript 11.0.3 
atomic-chrome 0.3.0 
atomic-rtags 1.3.0 
auto-detect-indentation 1.3.0 
auto-indent 0.5.0 
autoclose-html 0.23.0 
autocomplete-clang 0.11.3 
autocomplete-ctags 0.4.1 
autocomplete-emojis 2.5.0 
autocomplete-html-entities 0.1.0 
autocomplete-json 5.4.0 
autocomplete-modules 1.6.9 
autocomplete-paths 1.0.5 
autocomplete-python 1.8.63 
autocomplete-rt-jira 0.0.0 
block-comment-lines 0.2.4 
block-travel 1.0.5 
browser-plus 0.0.87 
build 0.67.0 
build-cmake 0.9.1 
build-tools 4.5.9 
busy 0.7.0 
busy-signal 1.4.0 
code-peek 1.4.18 
coffee-compile 0.25.0 
coffee-navigator 0.0.18 
color-picker 2.2.5 
cpp-refactor 2.2.3 
delete-lines 0.5.0 
disable-keybindings 0.6.0 
docblockr 0.9.4 
docker 0.7.0 
dockerletion 0.2.0 
file-icons 2.1.3 
find-selection 0.16.0 
fold-lines 0.2.2 
formatter-clangformat 1.0.1 
gist-it 0.9.2 
git-control 0.9.0 
git-diff-details 1.4.0 
git-log 0.4.1 
git-plus 7.6.0 
git-split-diff-hyperclick 0.3.12 
goto 1.8.3 
goto-definition 1.3.3 
goto-last-edit 0.3.2 
hey-pane 0.3.1 
highlight-line 0.12.0 
highlight-selected 0.13.1 
Hydrogen 1.11.2 
hyperclick 0.0.40 
incremental-search 5.2.2 
indent-guide-improved 1.4.12 
intentions 1.1.2 
json-colorer 1.0.0 
jumpy 3.1.3 
keybinding-cheatsheet 0.1.1 
keymap-disabler 0.1.1 
language-babel 2.57.7 
language-cpp14 0.6.2 
language-diff 0.7.0 
language-docker 1.1.7 
language-latex 1.0.0 
language-markdown 0.21.0 
last-cursor-position 0.9.2 
latex 0.43.0 
latex-completions 0.3.2 
line-count 0.5.0 
line-diff-details 1.8.0 
line-ending-converter 1.3.2 
lines 0.13.1 
lint 0.0.1 
linter 2.1.4 
linter-coffeescript 1.0.0 
linter-cpplint 2.0.1 
linter-docker 0.2.0 
linter-gcc 0.7.1 
linter-markdown 4.0.0 
linter-pylama 0.8.16 
linter-pylint 2.0.1 
linter-tidy 2.3.1 
linter-ui-default 1.2.3 
linter-write-good 0.9.0 
MagicPython 1.0.9 
markdown-folder 0.5.0 
markdown-pdf 1.5.0 
markdown-preview-plus 2.4.9 
markdown-scroll-sync 2.1.2 
markdown-toc 0.4.2 
markdown-writer 2.6.4 
merge-conflicts 1.4.4 
minimap 4.27.1 
minimap-autohide 0.10.1 
minimap-bookmarks 0.4.2 
minimap-codeglance 0.4.6 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.0 
minimap-pigments 0.2.2 
minimap-selection 4.4.0 
minimap-split-diff 0.3.7 
minimap-titles 1.11.0 
monokai 0.22.0 
monokai-seti 0.7.0 
multi-cursor 2.1.5 
multi-cursor-plus 1.2.0 
narrow 0.40.0 
navigate 0.1.17 
open-in-browsers 0.0.19 
open-recent 5.0.0 
open-terminal-here 2.3.0 
opened-files 0.3.6 
pdf-view 0.57.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
pretty-json 1.6.3 
project-manager 3.3.4 
python-debugger 0.2.0 
python-indent 1.0.2 
python-iresolve 0.0.3 
python-isort 0.0.7 
python-line-profiler 0.2.1 
python-tools 0.6.9 
python-yapf 0.13.0 
qolor 0.4.1 
recent-files-fuzzy-finder 0.3.1 
regex-railroad-diagram 0.17.0 
remote-edit 1.9.0 
Remote-FTP 0.10.7 
remote-sync 4.1.5 
run-command 0.3.2 
run-command2 1.12.2 
script 3.14.1 
selection-highlight 0.1.6 
shell-it 0.2.1 
simple-drag-drop-text 0.3.4 
sort-lines 0.14.0 
split-diff 1.3.0 
sublime-block-comment 0.5.1 
Sublime-Style-Column-Selection 1.7.4 
symbols-tree-view 0.14.0 
sync-settings 0.8.1 
tabs-to-spaces 1.0.3 
token-navigation 1.4.8 
trailing-spaces 0.4.0 
tree-view-git-status 1.3.1 
tree-view-search-bar 0.1.3 
vim-mode-plus 0.91.0 
Zen 0.16.4 
```

**Comment by t9md** [comment]
I'm not sure this is really narrow's fault.

Can you reproduce always?
Removing narrow and re-install solve problem?
Re-install Atom itself solve problem?

**Comment by balta2ar** [comment]
You're right, I left only narrow plugin on and tried project symbols, it worked fine. I'll bisect and find the the misbehaved plugin a little later.
