### ISSUE TITLE
Scan bug (0.65.1)

### ISSUE THREAD

**Issue by slavaGanzin** [t9md/atom-narrow#304]
Hello @t9md.

I updated narrow and tried to use scan, but get this:

```js
Uncaught (in promise) TypeError: editor.buffer.groupLastChanges is not a function
    at narrowEditor.withIgnoreChange (/home/vganzin/.config/.atom/packages/narrow/lib/ui.js:698:21)
    at NarrowEditor.withIgnoreChange (/home/vganzin/.config/.atom/packages/narrow/lib/narrow-editor.js:160:5)
    at Ui.renderItems (/home/vganzin/.config/.atom/packages/narrow/lib/ui.js:689:23)
    at reducers.reduce (/home/vganzin/.config/.atom/packages/narrow/lib/item-reducer.js:214:35)
    at Array.reduce (native)
    at ItemReducer.reduce (/home/vganzin/.config/.atom/packages/narrow/lib/item-reducer.js:213:19)
    at refreshDisposables.CompositeDisposable.onDidUpdateItems.items (/home/vganzin/.config/.atom/packages/narrow/lib/ui.js:746:26)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Ui.emitDidUpdateItems (/home/vganzin/.config/.atom/packages/narrow/lib/ui.js:77:45)
    at Ui.refresh (/home/vganzin/.config/.atom/packages/narrow/lib/ui.js:769:14)
```

Atom    : 1.24.0-beta3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
narrow: 0.65.1

I downgraded to 0.65.0 and everything works fine

**Comment by t9md** [comment]
Sorry, the reason is your atom version is way behind of latest version.
Why you use such an old version, any reason?

**Comment by slavaGanzin** [comment]
Thanks!

 > Why you use such an old version, any reason?
AUR Package that I used to use was orphaned sometime ago. And I didn't notice this because "it just works" :)
