### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getContainer' of undefined

### ISSUE THREAD

**Issue by awilkins** [t9md/atom-narrow#306]
Was closing tabs with middle click, Narrow window was the last tab to be closed.

**Atom**: 1.31.0-beta1 x64
**Electron**: 2.0.7
**OS**: Ubuntu 16.04.5
**Thrown From**: [narrow](https://github.com/t9md/atom-narrow) package 0.65.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getContainer' of undefined

```
At /home/awilkins/.atom/packages/narrow/node_modules/atom-outlet/lib/utils.js:66

TypeError: Cannot read property 'getContainer' of undefined
    at getLocationForItem (/packages/narrow/node_modules/atom-outlet/lib/utils.js:66:5)
    at getNextLocation (/packages/narrow/node_modules/atom-outlet/lib/index.js:93:44)
    at relocate (/packages/narrow/node_modules/atom-outlet/lib/index.js:100:20)
    at Ui.relocate (/packages/narrow/lib/ui.js:420:29)
    at Ui.onTabBarDoubleClick (/packages/narrow/lib/ui.js:400:12)
```

### Commands

```
 33x -7:04.6.0 vim-mode-plus:move-left (input.hidden-input)
  5x -7:02.1.0 core:delete (input.hidden-input)
     -7:00.9.0 vim-mode-plus:move-to-last-character-of-line (input.hidden-input)
     -7:00.6.0 vim-mode-plus:move-left (input.hidden-input)
     -6:59.9.0 vim-mode-plus:move-right (input.hidden-input)
     -6:59.7.0 core:delete (input.hidden-input)
     -6:59.2.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -6:58.5.0 ex-mode:open (input.hidden-input)
  3x -6:58.5.0 blur (input.hidden-input)
     -6:58.2.0 core:confirm (input.hidden-input)
 35x -6:58.2.0 blur (input.hidden-input)
  3x -3:08.7.0 core:backspace (input.hidden-input)
     -3:03.0 github:commit (input.hidden-input)
 10x -2:59.4.0 blur (input.hidden-input)
     -2:41.9.0 github:commit (input.hidden-input)
 28x -2:38.5.0 blur (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.1 
atom-easy-jsdoc 4.12.5 
atom-html-preview 0.2.5 
atom-ide-ui 0.13.0 
atom-jinja2 0.6.0 
autocomplete-modules 2.2.0 
autocomplete-paths 2.12.2 
editorconfig 2.2.2 
ex-mode 0.18.0 
file-icons 2.1.24 
file-types 1.0.1 
ghost-text 0.0.1 
graphviz-preview-plus 1.5.5 
highlight-selected 0.14.0 
ide-css 0.3.0 
ide-yaml 0.4.4 
language-ansible 0.2.2 
language-babel 2.85.0 
language-docker 1.1.8 
language-dot 1.7.0 
language-freebasic 0.0.10 
language-gherkin 1.0.4 
language-graphql 0.10.1 
language-groovy 0.7.0 
language-haskell 1.17.8 
language-ini 1.20.0 
language-kotlin 0.5.0 
language-lua 0.9.11 
language-markdown 0.26.0 
language-nginx 0.8.0 
language-nunjucks 4.2.1 
language-ocaml 1.9.5 
language-plantuml 0.2.0 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-terraform 0.8.1 
language-thrift 1.0.2 
linter 2.2.0 
linter-csslint 2.0.1 
linter-docker 0.3.2 
linter-eslint 8.4.1 
linter-jshint 3.1.8 
linter-sass-lint 1.8.3 
linter-shellcheck 1.5.0 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
narrow 0.65.1 
node_modules undefined 
nuclide 0.346.0 
nuclide-format-js 0.0.47 
pigments 0.40.2 
plantuml-viewer 0.7.2 
prettier-atom 0.55.2 
regex-railroad-diagram 0.19.4 
rest-client 1.3.1 
set-syntax 0.4.0 
sort-lines 0.18.0 
teletype 0.13.3 
todo-show 2.3.2 
tool-bar 1.1.10 
vim-mode-plus 1.35.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
```

**Comment by slavaGanzin** [comment]
Off topic: @awilkins how did you get commands log?
```
 33x -7:04.6.0 vim-mode-plus:move-left (input.hidden-input)
  5x -7:02.1.0 core:delete (input.hidden-input)
  ...
```

**Comment by awilkins** [comment]
The above bug report was created by the Atom bug wizard, I have no idea how to do that manually :-)
