### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setScrollTop' of null /usr/share/atom-beta/resources/app.asar/src/text-editor-element.js:335

### ISSUE THREAD

**Issue by averrin** [t9md/atom-narrow#40]
Just hit enter in narrow pane

Hide Stack Trace
TypeError: Cannot read property 'setScrollTop' of null
    at atom-text-editor.TextEditorElement.setScrollTop (/usr/share/atom-beta/resources/app.asar/src/text-editor-element.js:335:28)
    at Search.restoreEditorState (/home/alexeynabrodov/.atom/packages/narrow/lib/utils.coffee:82:19)
    at Search.module.exports.Base.destroy (/home/alexeynabrodov/.atom/packages/narrow/lib/provider/base.coffee:63:6)
    at UI.module.exports.UI.destroy (/home/alexeynabrodov/.atom/packages/narrow/lib/ui.coffee:37:16)
    at /home/alexeynabrodov/.atom/packages/narrow/lib/ui.coffee:26:36
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.destroyed (/usr/share/atom-beta/resources/app.asar/src/text-editor.js:550:20)
    at TextEditor.module.exports.Model.destroy (/usr/share/atom-beta/resources/app.asar/src/model.js:31:58)
    at UI.module.exports.UI.confirm (/home/alexeynabrodov/.atom/packages/narrow/lib/ui.coffee:149:21)
    at atom-text-editor.atom.commands.add.core:confirm (/home/alexeynabrodov/.atom/packages/narrow/lib/ui.coffee:42:27)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app.asar/src/command-registry.js:259:29)
    at /usr/share/atom-beta/resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:3:59)

**Comment by t9md** [comment]
What the provider?(e.g. `narrow:lines`, `narrow:folds` etc).
I need this info.

**Comment by averrin** [comment]
Hmm, i think it was `narrow:search`

**Comment by t9md** [comment]
I saw this error in old version.
But in recent 16days, the code is drastically changed.
I don't see for a couple of days.

So will close now.
If you still see same error, then re-open then.
