### ISSUE TITLE
Uncaught TypeError: onDidAddVimState is not a function

### ISSUE THREAD

**Issue by codedmart** [t9md/atom-narrow#5]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.5
**Thrown From**: [narrow](https://github.com/t9md/atom-narrow) package, v0.4.0

### Stack Trace

Uncaught TypeError: onDidAddVimState is not a function

```
At /Users/bmartin/.atom/packages/narrow/lib/main.coffee:58

TypeError: onDidAddVimState is not a function
    at Object.module.exports.consumeVim (/Users/bmartin/.atom/packages/narrow/lib/main.coffee:58:16)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tabs",
      "atomatigit",
      "terminal-plus",
      "vim-mode",
      "vim-surround",
      "ex-mode"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "nucleus-dark-ui",
      "dark-base16-eighties"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v1.3.0
atom-ternjs, v0.14.1
atom-typescript, v8.10.1
autoclose-html, v0.23.0
autocomplete-paths, v1.0.2
color-picker, v2.1.1
dark-base16-eighties, v0.0.0
emmet, v2.4.3
file-icons, v1.7.11
git-log, v0.4.1
ide-haskell-stack, v0.0.3
javascript-snippets, v1.2.1
language-diff, v0.4.0
language-elm, v1.3.4
language-haskell, v1.7.15
language-purescript, v0.7.0
linter, v1.11.4
linter-elm-make, v0.5.0
linter-eslint, v7.2.2
linter-tslint, v0.9.3
local-settings, v0.4.0
narrow, v0.4.0
nix, v2.1.0
nucleus-dark-ui, v0.7.22
project-manager, v2.9.7
react, v0.15.0
ruby-syntax-replacer, v0.5.1
save-session, v0.16.0
vim-mode-plus, v0.40.1

# Dev
No dev packages
```

**Comment by t9md** [comment]
Sorry, this is my fault, I've depending on vim-mode-plus's service which was not yet released.
I released new version of vim-mode-plus v0.41.0.
Try with this version of vim-mode-plus with narrow.

**Comment by codedmart** [comment]
No worries! Works great! Thanks for you work on these packages.

**Comment by t9md** [comment]
I'm in very active experimenting several Ideas, so every parts of this packages is not fixed, might frequently change. So pls be patient if you use this package now.
But I'm also glad that you use this and gave me kind feedback.
