### ISSUE TITLE
"observeVimStates is not a function" error when starting up Atom

### ISSUE THREAD

**Issue by codemonkey800** [t9md/atom-narrow#8]
So like the title says, I get the `observeVimStates is not a function` error whenever I startup Atom. I thought it was a problem with vmp but noticed that the error only happens if I have narrow installed.

Here's the stack trace and related info copied from Atom:

---

**Atom Version**: 1.6.2
**System**: "Arch Linux"
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.32.1

### Stack Trace

Failed to activate the vim-mode-plus package

```
At observeVimStates is not a function

TypeError: observeVimStates is not a function
    at Object.module.exports.consumeVim (/home/jeremy/.atom/packages/narrow/lib/main.coffee:72:16)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at ServiceHub.module.exports.ServiceHub.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (/usr/share/atom/resources/app.asar/src/package.js:350:71)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:184:16)
    at /usr/share/atom/resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:526:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:507:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:502:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:485:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:41:9)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ],
    "projectHome": "/home/jeremy/Devel",
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "vim-mode-plus": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-django, v0.3.2
atom-jade, v0.3.0
atom-material-syntax, v0.4.6
atom-material-ui, v1.2.13
auto-detect-indentation, v1.1.0
autocomplete-cmake, v0.3.1
autocomplete-emojis, v2.5.0
autocomplete-html-entities, v0.1.0
clip-history, v0.2.1
color-picker, v2.2.2
cursor-history, v0.5.9
docblockr, v0.7.3
editorconfig, v1.4.1
file-icons, v1.7.16
haskell-grammar, v0.4.0
highlight-line, v0.11.1
highlight-selected, v0.11.2
language-babel, v2.31.0
language-bazel, v0.3.1
language-cmake, v0.2.0
language-docker, v1.1.6
language-fish-shell, v1.0.4
language-groovy, v0.6.0
language-ini, v1.16.0
language-kotlin, v0.4.0
language-latex, v0.6.1
language-lua, v0.9.4
language-mips, v0.2.0
language-ocaml, v1.1.2
language-swift, v0.4.0
language-thrift, v1.0.2
latexer, v0.3.0
linter, v1.11.14
linter-chktex, v1.3.0
linter-csslint, v1.3.2
linter-docker, v0.1.2
linter-eslint, v7.2.3
linter-flake8, v1.13.2
linter-gcc, v0.6.14
linter-jade, v0.3.2
linter-javac, v1.9.4
linter-jsonlint, v1.3.0
linter-kotlin, v0.1.0
linter-lua, v1.0.2
linter-markdown, v1.5.2
linter-shellcheck, v1.2.0
linter-swiftc, v2.0.0
merge-conflicts, v1.4.4
minimap, v4.24.7
minimap-cursorline, v0.2.0
minimap-find-and-replace, v4.5.1
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
narrow, v0.5.2
nuclide, v0.136.0
pdf-view, v0.50.0
pigments, v0.31.1
quick-highlight, v0.5.0
release-notes, v0.53.0
sync-settings, v0.7.2
tool-bar, v1.0.0
trailing-spaces, v0.3.2
vim-mode-plus, v0.32.1
vim-mode-plus-move-selected-text, v0.6.0
vim-mode-plus-move-to-symbols, v0.1.5
vim-mode-plus-replace-with-execution, v0.1.2
vim-mode-plus-subword-movement, v0.2.2

# Dev
No dev packages
```

**Comment by t9md** [comment]
Update Atom, then update to latest vim-mode v0.46.0("atom": ">=1.7.0" require).

The latest version of vim-mode-plus is v0.46.0.
Your version v0.32.1 is very old and not have `observeVimStates` provided.
As README of narrow explain, this package only works with latest version of vmp.
Unfortunately current Atom don't have version requirement for depending **atom** package(not *node package*).

**Comment by codemonkey800** [comment]
Oh wow, it's working now. For some reason, when running `apm upgrade`, it doesn't even list v0.46.0, and by default `apm install vim-mode-plus` will install v0.32.1.

Either way, thanks a lot! :smiley:

**Comment by codemonkey800** [comment]
![image](https://cloud.githubusercontent.com/assets/2176050/16717458/315b6bf4-46cb-11e6-8569-1e487b1a0b10.png)

Alright, I realize that I derped out here. It definitely was because I was running an older version of Atom, but I had no idea because the actual Atom package (well the binary distribution) on Arch is outdated. I am now running the latest version and have no problems at all.

However, I still have to thank  you because I would never have found that out on my own. So thank you! :smiley:

**Comment by t9md** [comment]
Since Atom is frequently updated with deprecating many API and hard for me to maintain compatibility  to older version of Atom, I'm specifying Atom version(engine version in package.json) in vim-mode-plus's package.json.
If you run old Atom, it can only install compatible version of vim-mode-plus.
If you run newer Atom it meed required engine version(=Atom version), that allow newer vim-mode-plus insalled.
